services:
    Cjm\Delivery\Application\:
        resource: '../src/Application'
        public: true
        bind:
            Cjm\Delivery\Domain\OrderRepositoryInterface: '@Cjm\Delivery\Infrastructure\Doctrine\OrderRepository'
